### ISSUE TITLE
Default configuration should be 25 minutes

### ISSUE THREAD

**Issue by ismayilkarimli** [niyazisuleymanov/termdoro#1]
By default pomodoro default is usually 25 minutes. It would make more sense for the default to be 25 minutes instead of 35 since that would be the expected behavior for the majority of users.

**Comment by niyazisuleymanov** [comment]
Fixed: [f682ad1](https://github.com/niyazisuleymanov/termdoro/commit/f682ad11e64bd7272d116d5aefbd9295d2735a1c)
